### ISSUE TITLE
Remove contributors from boilerplate

### ISSUE THREAD

**Issue by goodmind** [goodmind/treact#30]
Contributors emails are:
```
altay.aydemir@gmail.com
batuhanicoz@gmail.com
rjmunro@arjam.net
ufukomer@gmail.com
LAMAPB@li01r1d.lais.net
alexandr.bbm@gmail.com
adam@adamlav.in
pedropovedaq@gmail.com
bartholomaios@gmail.com
anjdreas@gmail.com
git@lk.vc
```

**Comment by sovietspaceship2** [comment]
is this resolved because there are none in the current code

**Comment by goodmind** [comment]
@sovietspaceship wut

**Comment by goodmind** [comment]
@sovietspaceship 
![image](https://user-images.githubusercontent.com/3275424/28738853-7cea3ec0-740f-11e7-8335-38b83971b2c4.png)

**Comment by sovietspaceship2** [comment]
that's the git history you can't change it without breaking the repo

**Comment by goodmind** [comment]
@sovietspaceship i will break

**Comment by goodmind** [comment]
I think its wrong to remove history

**Comment by sovietspaceship2** [comment]
я же тебе говорил лол
